# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "GCC2021 Training"
email: saskiahiltemann@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Website for the GCC2021 Training Week, June 28-July 2, 2021.
baseurl: "/events/gcc2021/training/" # the subpath of your site, e.g. /blog
url: "https://galaxyproject.org" # the base hostname & protocol for your site, e.g. http://example.com


registration_form: "https://www.vibconferences.be/events/gcc2021-virtual-edition"


twitter_username: gxy-training
github_username:  shiltemann

# can update to use an archived versions after the course
gtn_url: "https://training.galaxyproject.org/training-material/"
gtn_logo: "/assets/images/logos/00_GTNLogo300.png"
analytics_suffix: "?utm_source=smorgasbord&utm_medium=website&utm_campaign=gcc2021"

image_dir: /assets/images/
logo_dir: /assets/images/logos/


# support
support_platform: "Slack"
support_link: "https://gtnsmrgsbord.slack.com/"
support_join:
icebreaker_channel: "#social"
icebreaker_link:

# feedback
feedback_channel: "#feedback"
feedback_link:
feedback_survey_link:

#videos
video_platform: YouTube
video_prefix: "https://youtu.be/"



# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
